### ISSUE TITLE
Improve alias / UID behavior

### ISSUE THREAD

**Issue by chrisputnam9** [chrisputnam9/pssh#46]
**Todo:**
- [x] Turn off syncing
- [x] During clean, make sure each host has a 'additional_aliases' key
- [x] New Fxn - create map of host alias to host key and warn if any duplicates
- [x] During writeSSH, use new alias map instead of getHosts
- [x] During add, check for duplicate alias
  - Testing with `ca pssh add "/home/chris/.pssh/ssh_config_work.json" 1.1.1.1 google cmp`
  - [x] If duplicate alias, note the other host
  - [x] If duplicate alias, guide through alternate or automate
- [x] Fix up 'list' - show additional aliases
- [x] Fix up 'edit' - support looking for alternate alias
- [x] After 'edit' - make sure save works as expected (not creating new)
- [x] During *clean*, make sure key is same as main alias - warn if changing
- [x] During *edit*, make sure key is same as main alias - warn if changing
  - [x] Get keys first
  - [x] Prompt which file if multiple
  - [x] After edit, check for key change & collision
  - [x] Update warning prompt to list - try again or cancel
- [x] During edit, check for duplicate alias
- [x] Fix edit from list -> search
- [x] After 'edit' & 'delete' - make sure list displays properly (Not Array,Array)
- [x] Figure out why 'test' added to cmp gives warning, but not error, and not afterward
- [x] Merge alias_additional from multiple files
- [x] During clean, check for duplicate alias
- [x] Have export create a separate host entry for every available alias
  - [x] Debug - eg. at not working
- [x] Make sure search includes keys & all aliases
- [ ] #57

**Related Issues:**
 - [Support multiple aliases](https://github.com/chrisputnam9/pssh/issues/43)
 - [Clean data, eg spaces, from alias, port, etc](https://github.com/chrisputnam9/pssh/issues/7)
